<a href="https://colab.research.google.com/github/ankorn/arcanumsearch/blob/main/arc_retrieval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip -q install sentence-transformers[train] datasets faiss-gpu-cu12

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 47.5 MB/s eta 0:00:00:00:0100:01

In [2]:
from datasets import load_dataset
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
)
from sentence_transformers.losses import GISTEmbedLoss, MultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers
from sentence_transformers.evaluation import InformationRetrievalEvaluator
from sentence_transformers.util import mine_hard_negatives
import torch

/tmp/ipykernel_1655/1708220275.py:7: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers.losses import GISTEmbedLoss, MultipleNegativesRankingLoss
/tmp/ipykernel_1655/1708220275.py:8: DeprecationWarning: Importing from 'sentence_transformers.training_args' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.training_args' instead.
  from sentence_transformers.training_args import BatchSamplers
/tmp/ipykernel_1655/1708220275.py:9: DeprecationWarning: Importing from 'sentence_transformers.evaluation' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.evaluation' instead.
  from sentence_transformers.evaluation import InformationRetrievalEvaluator

In [3]:
dataset = load_dataset("pameydorke/arcanum-quests-queries-synthetic-v2")
train_dataset = dataset["train"]

train_dataset = train_dataset.rename_columns({
    "query": "anchor",
    "enhanced_document_text": "positive"
})

columns_to_keep = ["anchor", "positive"]
train_dataset = train_dataset.select_columns(columns_to_keep)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

README.md:   0%|          | 0.00/632 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00000-of-00001.parquet:   0%|          | 0.00/224k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/158k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/912 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/228 [00:00<?, ? examples/s]

In [4]:
model = SentenceTransformer('BAAI/bge-m3')
guide_model = SentenceTransformer('BAAI/bge-m3')

loss = GISTEmbedLoss(
    model=model,
    guide=guide_model,
    temperature=0.01
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [5]:
test_dataset = dataset["test"]

queries = {}
corpus = {}
relevant_docs = {}

unique_docs = {}
for idx, example in enumerate(test_dataset):
    doc_text = example['enhanced_document_text']
    if doc_text not in unique_docs:
        doc_id = f"doc_{len(unique_docs)}"
        unique_docs[doc_text] = doc_id
        corpus[doc_id] = doc_text

for idx, example in enumerate(test_dataset):
    query = example['query']
    doc_text = example['enhanced_document_text']
    doc_id = unique_docs[doc_text]
    query_id = f"query_{idx}"
    queries[query_id] = query
    relevant_docs[query_id] = {doc_id}

evaluator = InformationRetrievalEvaluator(
    queries=queries,
    corpus=corpus,
    relevant_docs=relevant_docs,
    name="arcanum-test",
    show_progress_bar=False,
)

In [6]:
training_args = SentenceTransformerTrainingArguments(
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    # gradient_accumulation_steps=2,
    warmup_ratio=0.1,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="steps",
    save_total_limit=2,
    batch_sampler=BatchSamplers.NO_DUPLICATES,
)

WARNING:sentence_transformers.base.training_args:The `warmup_ratio` argument is deprecated in Transformers v5+, and will also be removed from Sentence Transformers once support for Transformers v4 is dropped. Since you're using Transformers v5+, please use `warmup_steps` (as a float) to specify the warmup ratio instead.

In [7]:
trainer = SentenceTransformerTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    loss=loss,
    evaluator=evaluator,
)
trainer.train()

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=171, training_loss=0.18606704427065512, metrics={'train_runtime': 371.0107, 'train_samples_per_second': 7.374, 'train_steps_per_second': 0.461, 'total_flos': 0.0, 'train_loss': 0.18606704427065512, 'epoch': 3.0})

In [ ]:
import huggingface_hub

huggingface_hub.login()

In [10]:
model.push_to_hub("pameydorke/arcanum-quests-base-retriever-v3")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp7l_oza8b/tokenizer.json:  48%|####7     | 7.98MB / 16.8MB

  ...l_oza8b/model.safetensors:   0%|          | 7.21MB / 2.27GB

'https://huggingface.co/pameydorke/arcanum-quests-base-retriever-v3/commit/e98537515ccfa82ff11f7ccfa22302dd5d9ef6a0'

In [4]:
BASE_MODEL_NAME = 'pameydorke/arcanum-quests-base-retriever-v3'

In [5]:
model = SentenceTransformer(BASE_MODEL_NAME)

modules.json:   0%|          | 0.00/429 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/283 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/241 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/380 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/16.8M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

In [13]:
loss = MultipleNegativesRankingLoss(model=model)

In [6]:
# train_dataset_hard = mine_hard_negatives(
#     dataset=train_dataset,
#     model=model,
#     range_min=10,
#     range_max=100,
#     max_score=0.9,
#     num_negatives=3,
#     batch_size=16,
#     use_faiss=True,
# )
train_dataset_hard_default = mine_hard_negatives(
    dataset=train_dataset,
    model=model,
    num_negatives=1,
    range_min=10,
    range_max=50,
    sampling_strategy="top",
    use_faiss=True,
)

Found 907 unique queries out of 912 total queries.
Found an average of 1.006 positives per query.

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/29 [00:00<?, ?it/s]

Querying FAISS index: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]

Negative candidates mined, preparing dataset...
Metric       Positive       Negative     Difference
Count             912            912
Mean           0.6620         0.4447         0.2173
Median         0.6614         0.4434         0.2142
Std            0.0674         0.0322         0.0681
Min            0.4528         0.3441         0.0061
25%            0.6139         0.4227         0.1694
50%            0.6615         0.4435         0.2143
75%            0.7084         0.4643         0.2634
Max            0.8498         0.5498         0.4240

In [34]:
import torch.nn.functional as F

for i, row in train_dataset_hard_default.to_pandas().iterrows():
    if i < 3:
        continue
    
    if i > 5:
        break
    
    query_e = model.encode(row['anchor'], convert_to_tensor=True).unsqueeze(0)
    positive_e = model.encode(row['positive'], convert_to_tensor=True).unsqueeze(0)
    negative_e = model.encode(row['negative'], convert_to_tensor=True).unsqueeze(0)
    
    positive_score = F.cosine_similarity(query_e, positive_e).item()
    negative_score = F.cosine_similarity(query_e, negative_e).item()
    
    print(row['anchor'], '\n')
    print('P:', f"{positive_score:.2f}", ' | ', row['positive'], '\n')
    print('N:',f"{negative_score:.2f}", ' | ',  row['negative'], '\n')
    
    print('>' * 50, '\n', '\n', '\n')

strongbox steafast anvill

P: 0.62  |  The Innkeeper's Strongbox. Drop Yer Anchor Daniel Hallaway can be found in Black Root at his Inn Talking with him reveals the high prices for staying at his Inn If Hallaway has a Reaction Modifier of at least 41 then The Player can ask for a cheaper alternative Hallaway then further reveals that he has a family Strongbox at The Steadfast Anvil, with difficulties getting it back Hallaway will offer the quest to get his Strongbox back In return the player can stay at his Inn for free forever The Steadfast Anvil Garret Almstead can be found in Black Root at his Smithy Talking with him reveals that Hallaway brought the Stronbox to him for repair It comes to light that there is a difference in expectations between the two men over what repairs were required This can be resolved by Convince him to return the box free (CH 15) Pay him for the box, prices vary based on (CH 7-14) Lock pick The Chest that has the Strongbox Pick pocket Garret and use the Key to get into the Chest Kill him and loot his key and the Chest Drop Yer Anchor Once the Strongbox is recovered, return it to Daniel at his Inn When he asks how you obtained it, you can lie or tell the truth Each line gets a different (and sometimes humorous) response from him In all cases the player receives a reward of 3100 xp and free lodging forever at his Inn

N: 0.38  |  Move the Boulders. Theo Brightstart, the gnomish farmer wants you to move five boulders from his field into his farm cart. He will pay you 50 to 100 gold for your efforts. This requires at least 12 strength and will take up almost your entire inventory space. If you aren't strong enough, then you can use strength buffs like Elixir of Physical Prowess, Alcohol, Strength of Earth spell, etc.In order to get this quest, you must first complete the Kill the Wild Pigs quest for Theo.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



where do i get filament sword

P: 0.67  |  Free the Ghost of Bessie Toone. Rewards. If the deed is given to Percival: 1,700 experience 500 gold If the deed is given to Sarah: 4,500 experience Filament sword Boost in good alignment (+22, with 9 Charisma and Smoking Jacket) 3 Pure Ore will appear in the mine where Bessie Toone's spirit was pacing

N: 0.46  |  Escort Swyft to Tarant. A young elf villager, Swyft asks you to take her to Tarant. If you don’t take here there after a while she will get upset and leave.59 Swyft: Take her to Tarant safely. (Reward: 300-450 gold (with Haggle), 1700 XP.) p. 222

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



help free spirit from old mineshaft

P: 0.69  |  Free the Ghost of Bessie Toone. Rewards. If the deed is given to Percival: 1,700 experience 500 gold If the deed is given to Sarah: 4,500 experience Filament sword Boost in good alignment (+22, with 9 Charisma and Smoking Jacket) 3 Pure Ore will appear in the mine where Bessie Toone's spirit was pacing

N: 0.46  |  Rescue Tollo Underhill. If the party finds and rescues Tollo randomly (without being assigned by K'an Hua) then the rewards are still the same The Pits has some interesting loot, so exploring it in its entirety may be a consideration

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [20]:
training_args = SentenceTransformerTrainingArguments(
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,
    fp16=True,
    warmup_ratio=0.1,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="steps",
    save_total_limit=1,
)

trainer = SentenceTransformerTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset_hard,
    loss=loss,
    evaluator=evaluator,
)
trainer.train()

WARNING:sentence_transformers.base.training_args:The `warmup_ratio` argument is deprecated in Transformers v5+, and will also be removed from Sentence Transformers once support for Transformers v4 is dropped. Since you're using Transformers v5+, please use `warmup_steps` (as a float) to specify the warmup ratio instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

In [61]:
model.push_to_hub("pameydorke/arcanum-quests-retriever-with-hard-negatives")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpljhriwyp/tokenizer.json:  48%|####7     | 7.98MB / 16.8MB

  ...jhriwyp/model.safetensors:   1%|1         | 24.7MB / 2.27GB

'https://huggingface.co/pameydorke/arcanum-quests-retriever-with-hard-negatives/commit/49c85d3e99b6db7801e27bae5b4acdb598a61367'

In [ ]:
from sentence_transformers import SentenceTransformer
import torch
import torch.nn.functional as F

documents = list(dataset['train']['document_text']) + list(dataset['test']['document_text'])
links = list(dataset['train']['document_link']) + list(dataset['test']['document_link'])

doc_embeddings = model.encode(
    documents,
    convert_to_tensor=True,
    show_progress_bar=True,
    batch_size=32
)

def retrieve(query, top_k=5):
    query_embedding = model.encode(query, convert_to_tensor=True)

    similarities = F.cosine_similarity(query_embedding, doc_embeddings)

    scores, indices = torch.topk(similarities, k=top_k)

    return [
        {"score": float(scores[i]), "link": links[indices[i]], "text": documents[indices[i]]}
        for i in range(top_k)
    ]

Batches:   0%|          | 0/22 [00:00<?, ?it/s]

In [89]:
for t in ["bow master", "master of bow", "bow mastery quest", "azram star quest", "Strongbox quest"]:
  results = retrieve(t)
  for r in results:
      print(f"{r['score']:.4f} | {r['link']} | {r['text'][:100]}...")

  print('\n')

0.3788 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.3788 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.3788 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.3783 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master of Air by talking with Wek’ K’ene and taking his test. This involves getti...
0.3783 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master of Air by talking with Wek’ K’ene and taking his test. This involves getti...
0.3783 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master of Air by talking with Wek’ K’ene and taking his test. This involves getti...
0.3588 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.3588 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.3588 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.3041 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Necromatic White by talking with Bilko Gavin and taking his test. Game ...


0.4549 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.4549 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.4549 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.4450 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master of Air by talking with Wek’ K’ene and taking his test. This involves getti...
0.4450 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master of Air by talking with Wek’ K’ene and taking his test. This involves getti...
0.4450 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master of Air by talking with Wek’ K’ene and taking his test. This involves getti...
0.3545 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.3545 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.3545 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.3284 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Conveyance by talking with Ve’tura and taking her test. Once you get in...


0.5346 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.5346 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.5346 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | This quest is found in the "rumor" tab of the player's logbook, rather than in the "quest" tab If th...
0.4345 | https://arcanum.fandom.com/wiki/Gamble_with_Gurin_Rockharrow | This is the Mastery Quest for Gambling...
0.4345 | https://arcanum.fandom.com/wiki/Gamble_with_Gurin_Rockharrow | This is the Mastery Quest for Gambling...
0.4345 | https://arcanum.fandom.com/wiki/Gamble_with_Gurin_Rockharrow | This is the Mastery Quest for Gambling...
0.3125 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.3125 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.3125 | https://arcanum.fandom.com/wiki/Masters_of_Magick | You can become the Master Of Earth by talking with Addo Terrin and taking his test. This involves ge...
0.2834 | https://arcanum.fandom.com/wiki/Find_Dudley_Crosston | Black Root Kietzel Pierce can be found in Black Root at one of the local pubs Talking with him revea...


0.4678 | https://arcanum.fandom.com/wiki/Retrieve_Azram%27s_Star | Black Root Clarissa Shalmo can be found in Black Root at one of the local pubs Talking with her reve...
0.4678 | https://arcanum.fandom.com/wiki/Retrieve_Azram%27s_Star | Black Root Clarissa Shalmo can be found in Black Root at one of the local pubs Talking with her reve...
0.4678 | https://arcanum.fandom.com/wiki/Retrieve_Azram%27s_Star | Black Root Clarissa Shalmo can be found in Black Root at one of the local pubs Talking with her reve...
0.2024 | https://arcanum.fandom.com/wiki/The_Ancient_Game | 800 XP Mysterious Gem. When used, summons a level 50 naked halfling to assist in combat....
0.2024 | https://arcanum.fandom.com/wiki/The_Ancient_Game | 800 XP Mysterious Gem. When used, summons a level 50 naked halfling to assist in combat....
0.2024 | https://arcanum.fandom.com/wiki/The_Ancient_Game | 800 XP Mysterious Gem. When used, summons a level 50 naked halfling to assist in combat....
0.1948 | https://arcanum.fandom.com/wiki/The_Crystal_Ball | Delores Beston, in her home at 42 Polton Cross in Tarant, will ask you find a crystal ball for her. ...
0.1948 | https://arcanum.fandom.com/wiki/The_Crystal_Ball | Delores Beston, in her home at 42 Polton Cross in Tarant, will ask you find a crystal ball for her. ...
0.1948 | https://arcanum.fandom.com/wiki/The_Crystal_Ball | Delores Beston, in her home at 42 Polton Cross in Tarant, will ask you find a crystal ball for her. ...
0.1920 | https://arcanum.fandom.com/wiki/The_Sorcerous_Beast | From talking with the guard outside the isle of despair fort, you will learn that there is a sorcero...


0.4678 | https://arcanum.fandom.com/wiki/The_Innkeeper%27s_Strongbox | The Quest is botched if the player has stolen the Strongbox before accepting the quest, resulting in...
0.4678 | https://arcanum.fandom.com/wiki/The_Innkeeper%27s_Strongbox | The Quest is botched if the player has stolen the Strongbox before accepting the quest, resulting in...
0.4677 | https://arcanum.fandom.com/wiki/The_Innkeeper%27s_Strongbox | The Quest is botched if the player has stolen the Strongbox before accepting the quest, resulting in...
0.2669 | https://arcanum.fandom.com/wiki/Find_Friend_Cyrus | 4200 XP Stillwater Blade...
0.2669 | https://arcanum.fandom.com/wiki/Find_Friend_Cyrus | 4200 XP Stillwater Blade...
0.2669 | https://arcanum.fandom.com/wiki/Find_Friend_Cyrus | 4200 XP Stillwater Blade...
0.2564 | https://arcanum.fandom.com/wiki/The_Innkeeper%27s_Strongbox | Drop Yer Anchor Daniel Hallaway can be found in Black Root at his Inn Talking with him reveals the h...
0.2564 | https://arcanum.fandom.com/wiki/The_Innkeeper%27s_Strongbox | Drop Yer Anchor Daniel Hallaway can be found in Black Root at his Inn Talking with him reveals the h...
0.2564 | https://arcanum.fandom.com/wiki/The_Innkeeper%27s_Strongbox | Drop Yer Anchor Daniel Hallaway can be found in Black Root at his Inn Talking with him reveals the h...
0.2210 | https://arcanum.fandom.com/wiki/Destroy_the_Town%27s_Steam_Engine | Pickup Jongle's Package Fix the Town's Steam Engine...