In [1]:
%pip install -q datasets pyarrow

In [2]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset("pameydorke/arcanum-search-embs-csv")

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/390 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 19.7MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1153 [00:00<?, ? examples/s]

In [3]:
df = dataset['train'].to_pandas()
df = df.drop(columns='Unnamed: 0')
df

,content,url,embedding
0,Pyrotechnic Bow. Pyrotechnic Bow. The Pyrotech...,https://arcanum.fandom.com/wiki/Pyrotechnic_Bow,"[0.002190711908042431, 0.0052022249437868595, ..."
1,Original Post: What aspects of Arcanum do you ...,https://reddit.com/r/arcanum/comments/1w2qsg/w...,"[0.04089789837598801, -0.026058191433548927, -..."
2,"Tulla. Tulla. ""I can't STAND Tulla..everyone i...",https://arcanum.fandom.com/wiki/Tulla,"[-0.008103189058601856, 0.04381492733955383, 0..."
3,Succour Beast. Succour Beast. Succour Beast is...,https://arcanum.fandom.com/wiki/Succour_Beast,"[-0.054103221744298935, 0.04578685760498047, -..."
4,"Gar. Gar. ""He has the body of an Orc, but the ...",https://arcanum.fandom.com/wiki/Gar,"[-0.025474006310105324, 0.003153689904138446, ..."
...,...,...,...
1148,Character background. Bookworm. Character back...,https://arcanum.fandom.com/wiki/Character_back...,"[-0.05470237135887146, -0.015489425510168076, ..."
1149,Original Post: Can't Mod Random Encounter. I h...,https://reddit.com/r/arcanum/comments/wn68gh/c...,"[0.007532842922955751, -0.0052304393611848354,..."
1150,Looking Glass Rifle. Looking Glass Rifle. This...,https://arcanum.fandom.com/wiki/Looking_Glass_...,"[-0.04116610437631607, -0.016336340457201004, ..."
1151,Side Arms and Saltpeter. Side Arms and Saltpet...,https://arcanum.fandom.com/wiki/Side_Arms_and_...,"[0.015276065096259117, 0.027656786143779755, -..."
1152,Roan's Almanac of All Things Dwarven. Roan's A...,https://arcanum.fandom.com/wiki/Roan%27s_Alman...,"[0.0203640665858984, 0.01580522023141384, -0.0..."

In [4]:
df2 = load_dataset("pameydorke/arcanumsearch-cross-platform")['train'].to_pandas()
df2

README.md:   0%|          | 0.00/340 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  926kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1153 [00:00<?, ? examples/s]

,LINK,TITLE,TEXT
0,https://arcanum.fandom.com/wiki/%22Kerghan_and...,"""Kerghan and Persephone""","""Kerghan and Persephone"". ""Kerghan and Perseph..."
1,https://arcanum.fandom.com/wiki/AME_Page,AME Page,AME Page. AME Page. This Page is the starting ...
2,https://arcanum.fandom.com/wiki/A_Lair_of_Gyr_...,A Lair of Gyr Dolours,A Lair of Gyr Dolours. A Lair of Gyr Dolours. ...
3,https://arcanum.fandom.com/wiki/A_Mysterious_L...,A Mysterious Location,A Mysterious Location. A Mysterious Location. ...
4,https://arcanum.fandom.com/wiki/Accelerate_Hea...,Accelerate Healing,Accelerate Healing. Accelerate Healing. This s...
...,...,...,...
1148,https://www.nexusmods.com/arcanumofsteamworksa...,Considerate Weapon Mod,"Considerate Weapon Mod. Firearms, Throwing Wea..."
1149,https://www.nexusmods.com/arcanumofsteamworksa...,Let my Dog use the Train Mod,Let my Dog use the Train Mod. A simple mod tha...
1150,https://www.nexusmods.com/arcanumofsteamworksa...,Arcanum Crafting Manuals Cover Mod,Arcanum Crafting Manuals Cover Mod. Mod change...
1151,https://www.nexusmods.com/arcanumofsteamworksa...,Arcanum Improved Descriptions(AID) Mod,Arcanum Improved Descriptions(AID) Mod. Mod co...
1152,https://www.nexusmods.com/arcanumofsteamworksa...,Unofficial Arcanum Patch 2.02 by Drog Black Tooth,Unofficial Arcanum Patch 2.02 by Drog Black To...

In [5]:
title_mapping = dict(zip(df2['LINK'], df2['TITLE']))

df['title'] = df['url'].map(title_mapping)

In [6]:
df

,content,url,embedding,title
0,Pyrotechnic Bow. Pyrotechnic Bow. The Pyrotech...,https://arcanum.fandom.com/wiki/Pyrotechnic_Bow,"[0.002190711908042431, 0.0052022249437868595, ...",Pyrotechnic Bow
1,Original Post: What aspects of Arcanum do you ...,https://reddit.com/r/arcanum/comments/1w2qsg/w...,"[0.04089789837598801, -0.026058191433548927, -...",What aspects of Arcanum do you wish other game...
2,"Tulla. Tulla. ""I can't STAND Tulla..everyone i...",https://arcanum.fandom.com/wiki/Tulla,"[-0.008103189058601856, 0.04381492733955383, 0...",Tulla
3,Succour Beast. Succour Beast. Succour Beast is...,https://arcanum.fandom.com/wiki/Succour_Beast,"[-0.054103221744298935, 0.04578685760498047, -...",Succour Beast
4,"Gar. Gar. ""He has the body of an Orc, but the ...",https://arcanum.fandom.com/wiki/Gar,"[-0.025474006310105324, 0.003153689904138446, ...",Gar
...,...,...,...,...
1148,Character background. Bookworm. Character back...,https://arcanum.fandom.com/wiki/Character_back...,"[-0.05470237135887146, -0.015489425510168076, ...",Character background: Wild Half-Ogre
1149,Original Post: Can't Mod Random Encounter. I h...,https://reddit.com/r/arcanum/comments/wn68gh/c...,"[0.007532842922955751, -0.0052304393611848354,...",Can't Mod Random Encounter
1150,Looking Glass Rifle. Looking Glass Rifle. This...,https://arcanum.fandom.com/wiki/Looking_Glass_...,"[-0.04116610437631607, -0.016336340457201004, ...",Looking Glass Rifle
1151,Side Arms and Saltpeter. Side Arms and Saltpet...,https://arcanum.fandom.com/wiki/Side_Arms_and_...,"[0.015276065096259117, 0.027656786143779755, -...",Side Arms and Saltpeter
1152,Roan's Almanac of All Things Dwarven. Roan's A...,https://arcanum.fandom.com/wiki/Roan%27s_Alman...,"[0.0203640665858984, 0.01580522023141384, -0.0...",Roan's Almanac of All Things Dwarven

In [8]:
from datasets import Dataset

hf_ds = Dataset.from_pandas(df)

hf_ds

Dataset({
    features: ['content', 'url', 'embedding', 'title'],
    num_rows: 1153
})

In [ ]:
hf_ds.push_to_hub("pameydorke/arcanumsearch-embs", token='')

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
WARNING:datasets.arrow_dataset:Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmph3an09gk.parquet    :   3%|2         |  524kB / 19.0MB

Validating                    :           |   0%

CommitInfo(commit_url='https://huggingface.co/datasets/pameydorke/arcanumsearch-embs/commit/4014df89b3bef3d1098f4a74b22ca390efe2b329', commit_message='Upload dataset', commit_description='', oid='4014df89b3bef3d1098f4a74b22ca390efe2b329', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/pameydorke/arcanumsearch-embs', endpoint='https://huggingface.co', repo_type='dataset', repo_id='pameydorke/arcanumsearch-embs'), pr_revision=None, pr_num=None)